Bump the minimum Rust version to 1.25
This lets bindgen use `#[repr(align = …)]`, which removes the need
for dummy `__bindgen_align` zero-size array fields.

This field was only present with some versions of libclang (presumably),
which could cause build failures like:

```rust
error[E0560]: struct `generated::root::JS::Value` has no field named `__bindgen_align`sys
  --> /home/simon/projects/mozjs/src/jsval.rs:83:2
   |
83 |     __bindgen_align: [],
   |     ^^^^^^^^^^^^^^^ `generated::root::JS::Value` does not have this field
```